# For all available configuration settings, please go to:
#   https://docs.viktor.ai/docs/create-apps/references/viktor-config-toml

app_type = 'simple'
# assets_path = 'assets'
# packages = []
python_version = '3.12'  # '3.9' | '3.10' | '3.11' | '3.12'
# welcome_text = 'welcome.md'
